[package]
name = "poke-sim"
author = "doobent"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wee_alloc = { version = "0.4.5", optional = true }
wasm-bindgen = "0.2.78"

[profile.release]
opt-level = "s"